name: Internship Scraper

on:
  workflow_dispatch:

jobs:
  run-python:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: internships
          path: internships.csv
